In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from transformers import AutoTokenizer
from datasets import Dataset, load_dataset

from pathlib import Path

In [2]:
data_dir = Path("../data/interim/")
ckpt = "distilbert-base-uncased"

## Tokenize text

In [3]:
tokenizer = AutoTokenizer.from_pretrained(ckpt, use_fast=True)

In [4]:
df = pd.read_csv(data_dir/"wndp-api-ohe.csv")
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.dropna(inplace=True)
df.head()

,patient_id,text,terms,clinically_healthy,dermatologic_disease,gastrointestinal_disease,hematologic_disease,neurologic_disease,nonspecific,nutritional_disease,ocular_disease,physical_injury,respiratory_disease,urogenital_disease
0,2224052,"Orphaned. Body: fleas, flea dirt",['Clinically healthy'],1,0,0,0,0,0,0,0,0,0,0
1,554625,can't fly. expired shortly after intake,['Nonspecific'],0,0,0,0,0,1,0,0,0,0,0
2,2683764,Orphaned. Body: ECTOPALASHES - FLEAS,['Clinically healthy'],1,0,0,0,0,0,0,0,0,0,0
3,979650,Collision - Car. Fx- Humerus (L) ; Nutritional...,"['Neurologic disease', 'Nutritional disease', ...",0,0,0,0,1,0,1,0,1,0,0
4,1942311,"NSF, orphaned. NSF, orphaned",['Clinically healthy'],1,0,0,0,0,0,0,0,0,0,0

In [5]:
df.shape

(15636, 14)

In [6]:
sample = df.text[:5]
sample[3]

'Collision - Car. Fx- Humerus (L) ; Nutritional - Emaciation; Trauma - Head. Neurologic: Thought to be a DOA until touching Feathers / Fur / Skin: Punctured where broken humerus is Wings / Arms: Fx - Humerus (L) Compound'

In [7]:
tokenizer(sample[3])

{'input_ids': [101, 12365, 1011, 2482, 1012, 23292, 1011, 20368, 7946, 1006, 1048, 1007, 1025, 28268, 1011, 7861, 6305, 18963, 1025, 12603, 1011, 2132, 1012, 11265, 10976, 27179, 1024, 2245, 2000, 2022, 1037, 2079, 2050, 2127, 7244, 12261, 1013, 6519, 1013, 3096, 1024, 26136, 14890, 2094, 2073, 3714, 20368, 7946, 2003, 4777, 1013, 2608, 1024, 23292, 1011, 20368, 7946, 1006, 1048, 1007, 7328, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [8]:
tokens = tokenizer.tokenize(sample[3])
tokens

['collision',
 '-',
 'car',
 '.',
 'fx',
 '-',
 'hume',
 '##rus',
 '(',
 'l',
 ')',
 ';',
 'nutritional',
 '-',
 'em',
 '##ac',
 '##iation',
 ';',
 'trauma',
 '-',
 'head',
 '.',
 'ne',
 '##uro',
 '##logic',
 ':',
 'thought',
 'to',
 'be',
 'a',
 'do',
 '##a',
 'until',
 'touching',
 'feathers',
 '/',
 'fur',
 '/',
 'skin',
 ':',
 'pun',
 '##cture',
 '##d',
 'where',
 'broken',
 'hume',
 '##rus',
 'is',
 'wings',
 '/',
 'arms',
 ':',
 'fx',
 '-',
 'hume',
 '##rus',
 '(',
 'l',
 ')',
 'compound']

In [9]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[12365,
 1011,
 2482,
 1012,
 23292,
 1011,
 20368,
 7946,
 1006,
 1048,
 1007,
 1025,
 28268,
 1011,
 7861,
 6305,
 18963,
 1025,
 12603,
 1011,
 2132,
 1012,
 11265,
 10976,
 27179,
 1024,
 2245,
 2000,
 2022,
 1037,
 2079,
 2050,
 2127,
 7244,
 12261,
 1013,
 6519,
 1013,
 3096,
 1024,
 26136,
 14890,
 2094,
 2073,
 3714,
 20368,
 7946,
 2003,
 4777,
 1013,
 2608,
 1024,
 23292,
 1011,
 20368,
 7946,
 1006,
 1048,
 1007,
 7328]

In [10]:
tokenizer.decode(ids)

'collision - car. fx - humerus ( l ) ; nutritional - emaciation ; trauma - head. neurologic : thought to be a doa until touching feathers / fur / skin : punctured where broken humerus is wings / arms : fx - humerus ( l ) compound'

In [11]:
tokenizer.decode(tokenizer(sample[3])["input_ids"])

'[CLS] collision - car. fx - humerus ( l ) ; nutritional - emaciation ; trauma - head. neurologic : thought to be a doa until touching feathers / fur / skin : punctured where broken humerus is wings / arms : fx - humerus ( l ) compound [SEP]'

## Build the dataset

In [12]:
# Pick only the columns we need for the model
df = df[list(set(df.columns).difference({"patient_id", "terms"}))]
df.head()

,clinically_healthy,nutritional_disease,text,neurologic_disease,ocular_disease,physical_injury,hematologic_disease,nonspecific,dermatologic_disease,gastrointestinal_disease,respiratory_disease,urogenital_disease
0,1,0,"Orphaned. Body: fleas, flea dirt",0,0,0,0,0,0,0,0,0
1,0,0,can't fly. expired shortly after intake,0,0,0,0,1,0,0,0,0
2,1,0,Orphaned. Body: ECTOPALASHES - FLEAS,0,0,0,0,0,0,0,0,0
3,0,1,Collision - Car. Fx- Humerus (L) ; Nutritional...,1,0,1,0,0,0,0,0,0
4,1,0,"NSF, orphaned. NSF, orphaned",0,0,0,0,0,0,0,0,0

In [13]:
# Split dataset into train, val & test set
_ds = (Dataset
          .from_pandas(df)
          .train_test_split(test_size=0.15, 
                            shuffle=True)
     )
ds = _ds["train"].train_test_split(test_size=0.2)
ds["val"] = ds.pop("test")
ds["test"] = _ds["test"]

In [14]:
ds = ds.remove_columns(column_names=["__index_level_0__"])

In [15]:
labels = sorted(ds["train"].column_names)
labels.remove("text")
labels

['clinically_healthy',
 'dermatologic_disease',
 'gastrointestinal_disease',
 'hematologic_disease',
 'neurologic_disease',
 'nonspecific',
 'nutritional_disease',
 'ocular_disease',
 'physical_injury',
 'respiratory_disease',
 'urogenital_disease']

In [16]:
# Add labels to the dataset as float (pytorch excepts float tensors)
ds = ds.map(lambda row: {"labels": [float(row[l]) for l in labels]})

Map:   0%|          | 0/10632 [00:00<?, ? examples/s]

Map:   0%|          | 0/2658 [00:00<?, ? examples/s]

Map:   0%|          | 0/2346 [00:00<?, ? examples/s]

In [17]:
ds["train"][0]

{'clinically_healthy': 1,
 'nutritional_disease': 0,
 'text': 'No patient info. Too young',
 'neurologic_disease': 0,
 'ocular_disease': 0,
 'physical_injury': 0,
 'hematologic_disease': 0,
 'nonspecific': 0,
 'dermatologic_disease': 0,
 'gastrointestinal_disease': 0,
 'respiratory_disease': 0,
 'urogenital_disease': 0,
 'labels': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}

Let us look at how long is each of the text description

In [18]:
text_stats = np.array([len(row.split()) if row else 0 for row in ds["train"]["text"]])

In [19]:
#sns.histplot(text_stats, bins=20, kde=True)

In [20]:
#(text_stats < 3).sum()/len(text_stats)

In [21]:
#(text_stats > 128).sum()/len(text_stats)

1% of the data have words more than 128 words

In [22]:
for row in ds["train"]["text"]:
    if len(row.split()) < 3:
        print(row)

Cat contact
Orphan. Healthy
orphaned
sick
Orphaned. Orphaned
Kidnapped. NSF
Orphaned. Healthy
Unknown. NSF
Orphaned. Healthy
NSF
Orphaned. Healthy
Orphaned. IHI
NSF. NSF
Unknown
Onshore. NSF
Orphan
orphaned
Orphaned. Healthy
Not welcome
Orphan. Orphan
Sick/Weak
Undetermined. Undetermined
orphan. orphan
Orphan. Healthy
beached
Juv Displaced
Hatched CRU
Orphan. CH
Orphaned. Non-viable
Beached. Thin
weak
NSF. NSF
Orphaned. Orphan
unknown. NSF
grounded. Salmonellosis
grounded. hypothermia
emaciated. emaciated
Beached
beached
Abandoned. Orphaned
Kidnapped. Healthy
orphan. orphan
Injury. Injury
Displaced. Displaced
sick
Orphaned/Abandoned. Dehydration
ill
nest destroyed
Orphaned. NSF
weak
orphan. orphan
weak
Orphan
downed. Downed
Sick/Weak
wont fly
unknown. orphan
Beached
Orphan
Grounded. Healthy
sick
Orphaned. NSF
Beached. NSF
NSF. NSF
orphaned. orphaned
Trichomonoza. Trichomonosis
Orphaned. Healthy
NSF. NSF
Oiled
Hit window
Orphaned. Healthy
Emaciated. Emaciated
DOA. unknown
Sick. *Poxvirus
sick
Displaced. Displaced
Undetermined. Undetermined
Trichomonosis. Trichomonosis
nest destroyed
beached. NSF
orphan. orphan
sick
Sick/Weak
Beached
orphaned
Cat contact
NSF. NSF
nest destroyed
orphaned
Weak
Orphaned. NSF
lethargic. lethargic
sick/weak/injured
Beached
Cat contact
Orphan. Lethargic
unknown. Moribund
sick, orphaned
injury. injury
Hatched CRU
Orphaned. orphaned/degloving
NSF. NSF
on ground
DA/ Beached
Orphaned. NSF
Displaced. Displaced
Displaced. Displaced
oiled. Oiled
Orphaned. Healthy
Dumped/Lost. NSF
beached
beached. NSF
Orphan. Orphan
Sick
Fleas
ophaned
possible pox
NSF. NSF
Beached. emaciated
NSF. NSF
NSF. NSF
surrender. healthy
orphaned
orphan. orphan
Orphaned. Orphaned
Orphan. Healthy
Weak. Weak
Kidnapped. Orphan
Beached
sick
Healthy. Healthy
NSF. NSF
Lethargic. Lethargic
nest destroyed
Trichomonosis. Emaciated
Hawk caught
Weak. Weak
Grounded. Emaciated
Sick/Weak
Orphan. Orphan
Via vet
Orphan. Orphan
Beached
Orphaned
grounded. paraplegia
Emaciated
sneezing, lethargic
Orphaned. Orphan
Orphaned/Baby. NSF
Orphan
Orphan. Healthy
Beached
Grounded
NSF. NSF
NSF. NSF
Orphaned
Orphaned
Beached
sick
Grounded. Healthy
Weak
orphaned
NSF
Oiled. Oiled
hit window
Emaciated/Dehydrated/Trich. Emaciated/Trich
Beached. Emaciated
Grounded. Emaciated
orphaned
Displaced. Displaced
not specified
Orphaned. Releasable
Orphaned. NSF
Sick/Weak
Orphaned. Hypothermia
Unknown. NSF
Grounded. Orphaned
Not flying
NSF. NSF
Orphan. Orphan
NSF. NSF
Collision
Sick/Weak
Orphaned
Unknown
sick
DA
hit window
Cat caught
grounded. malnourished
Orphaned
injury. injury
Weak
head trauma
Displaced. Displaced
Orphan. Orphan
Unknown. Mites
Orphaned. Healthy
Birdnapped. NSF
Kidnapped. Orphan
Cat contact
orphaned
Orphan. Emaciated
Sick/Weak
Orphaned. DOA
Orphan. Healthy
Orphan. Healthy
Beached
unknown. Emaciated
dog caught
Orphan. Orphan
Grounded. Healthy
Displaced. Displaced
Orphaned. NSF
Orphaned. Healthy
undetermined. Paralysis
Displacement. NSF
Nest destroyed
lacerated back
Orphaned. NSF
DA/ Beached
Beached. Emaciated
orphan. QAR
Orphan. Hipocalcemie
orphaned. ORPHAN
Beached
Collision. NSF
Orphaned. Orphan
Orphaned, Sick/Weak
Unknown. Kidnapped
Beached. Oiled
NSF
avian pox
Orphaned. Healthy
NSF. NSF
Unknown
unknown. DOA
Sick/Weak
unknown
Sick/Weak
surrender. Healthy
NSF. NSF
Orphan. Orphan
HBC
Orphaned. NSF
Orphan. Orphan
Orphaned. Degloving
orphaned. Developmental
sick
Orphaned. Orphan
Unknown. NSF
ill
Orphan
beached
NSF. NSF
DA
Beached
Orphaned. **Healthy
Weak. Weak
Orphaned. Healthy
Orphaned. Displaced
Entangled. Healthy
HBC
NSF. NSF
orphaned. Healthy
Orphaned. DOA
Grounded. Healthy
orphaned
Sick. Emaciated
underweight. lungworm
Orphan. Healthy
Oiled
Cat contact
Beached
Displaced. Displaced
possible DA
Beached. Dying
Undetermined. Undetermined
orphan. orphan
Weak
Healthy
Weak
orphan. orphan
oil. anemia
Beached. Emaciated
Healthy. Healthy
Orphaned. Non-viable
injured
NSF. NSF
Cat contact
orphaned
Orphaned, weak
Orphaned
Orphaned. orphan
Beached
Grounded. Healthy
NSF. NSF
NSF. NSF
Electrocution. Electrocution
Not specified
Orphan. Orphan
sick
unknown
orphaned. NSF
?. Healthy
Healthy
Orphan. Orphan
Sick/Weak
sick
Orphaned. displaced
ill. Cold
NSF. NSF
BAR. Orphan
Displaced. Displaced
Unknown. NSF
Torticollis. Torticollis
HBC. Dehydration/emaciation
Displaced. Displaced
Abandoned
Orphan. Healthy
Injured
NSF. NSF
Orphaned
surrender. Healthy
sick
Orphan. Orphan
Lethargic. Lethargic
Healthy
orphaned, lethargic
Orphaned
Sick/Weak
lethargic
orphaned. orphan
Healthy
Orphan. Healthy
Healthy. Healthy
orphan. orphan
orphaned
Unknown
tree feld
unknown
Orphaned
Injury. injury
Orphan. Pink
young. orphaned
Kidnapped. NSF
orphaned
Orphaned. Orphan
Penile Prolapse
Orphan. ***Emaciated
orphaned
cat caught
Nest destroyed
Orphaned. orphan
Orphan. Orphan
sick
Orphan. Orphan
Cat contact
Orphan. Healthy
injured
NSF. NSF
Grounded. Seizures
Unknown. DOA
Undetermined. Undetermined
Undetermined. Undetermined
NSF. NSF
Orphaned. NSF
Injury
unknown. NSF
Sick/Weak
NSF. NSF
orphan. orphan
injured wing/leg
Orphaned. Healthy
heavily oiled
Orphaned
sick/injured
orphaned. NSF
Orphan. Healthy
HBC. Dehydration/emaciation
Orphaned. Non-viable
Appeared sick/injured
Unknown. Undetermined
Orphaned
Beached
Hit window
weak/ sick
Orphaned. Healthy
grounded. Orphaned
Cat contact
Weak
Orphaned. Orphaned
Poison
Grounded. Healthy
Orphan. CH
lethargic
can't fly
Orphan. Healthy
Orphan. Orphan
Displacement. NSF
NSF. NSF
Cat contact
orphaned
Orphaned. NSF
Juvie
Grounded. DOA
Hatched CRU
orphaned
can't fly
Orphan. Healthy
Orphan. Healthy
Hit window
orphan. orphan
Injury. Stunned
Orphan. Healthy
tree felled
NSF. NSF
Baby. Baby
Emaciation. Emaciated
Orphan. Orphan
Beached. NSF
appeared sick/injured
unknown- injury
Orphaned. Orphan
weak
Sick/Weak. Mites
Grounded. Healthy
Trauma. Healthy
orphaned. Orphaned
Healthy
Weak. Weak
orphaned
Orphaned. IHI
Orphan. Healthy
Sick. Sick
Orphaned. NSF
Beached. NSF
Injury
NSF. NSF
injured. Orphaned
Oiled
physical trauma
Beached. Emaciated
sick
orphaned
Mange. Mange/emaciation/dehydration
beached. Beached
Beached
injured leg
Beached. sick
NSF. NSF
orphaned. macrocephaly
Orphaned
beached. Emaciated
NSF. NSF
orphan
nest destroyed
Beached. DOA
NSF. NSF
Beached
Orphaned
orphaned
orphaned
BAR. Orphan
Ill
unknown. Emaciated
Unknown. NSF
orphaned
Orphan
Healthy, dehydrated
Neurological Symptoms
Beached. NSF
injured. neurological
Orphaned. Orphaned
Grounded. Emaciated
Sick/Weak
Weak. Weak
Grounded
Cat contact
Injured leg
Orphaned. Orphan
injured eye
orphaned
X
Healthy
orphaned
Poisoning. Poisoned
orphan. orphan
Healthy. Healthy
orphaned
NSF
Displaced. Displaced
Sick. Poxvirus
orphaned
Orphan. Healthy
Orphaned. orphan
Hit window
Beached
Unknown. NSF
sick, weak
Unknown. NSF
Orphaned
NSF. NSF
NSF. NSF
Grounded. Healthy
Sick/Weak
Sick. Weak
orphaned
NSf. NSF
Cat contact
Orphaned. NSF
Injury. Stunned
NSF
NSF
Dog contact
Orphan
oiled. Oiled
Orphaned. NSF
weak, lethargic
Beached. Emaciated
Unknown. DOA
Orphaned. Orphaned
Displaced. Displaced
Baby. Baby
Orphan. Healthy
Cat caught
Orphaned
NSF. NSF
Healthy. Healthy
NSF. NSF
Orphaned. Healthy
Rodenticide
Orphan. Healthy
Not specified
Beached. NSF
unknown. DOA
Sick/Weak
weak
Trichomonosis. Trichomonosis
weak
sick/weak
Orphaned. Orphan
HBC
orphan. orphan
Beached. Emaciated
nestling
Beached/ DA
Displaced. Displaced
Orphaned
Sick. Weak
Orphaned

In [23]:
for row in ds["train"]["text"]:
    if len(row.split()) > 200:
        print(len(row.split()), row)
        print("-" * 20)

236 not moving much, not flighted when approached, appeared injured. B1 - Infectious/systemic disease, B2 - toxicosis. Neurologic: Generalized weakness, ataxia GI / Vent: Melena Feathers / Fur / Skin: Poor feather quality, feather lice Wings / Arms: Small abrasion on left distal phalanges Legs / Feet / Hocks: Small, chronic/necrotic open wounds between webbing of digits 2 and 3 and digits 3 and 4 on both feet. A: Juvenile WOST 24-113 was admitted after being found not moving much and not flying away. PE showed signs of general weakness, ataxia, bad feather quality, feather lice, small abrasion on left distal phalanges, melena, and small chronic, necrotic open wounds on patient's webbing. Suspect systemic disease - infectious vs toxicosis vs other. Guarded prognosis assigned to patient for survival - will depend on patient's response to supportive care.
P: Plan to give patient IVLE 15 ml/kg over one hour followed by Norm-R IVF at 80 ml/kg/d. Will start patient on metronidazole 25 mg/kg PO BID and gabapentin 20 mg/kg PO BID given clinical symptoms. Consider d/c both in 5 days if GI signs resolve and feet are healing. Plan to check for melena BID, FF 2-5% BW P-Care with 1/2 Sea Tab PO SID. Will also check feet/carpi/keel SID, clean/express cloaca PRN TID, and auscultate BID while on IVF. Plan to check wounds and clean with betadine. Will consider debriding if necessary once patient is more stable. MMC
--------------------
232 Collision - Car (Jason found patient, and transferred to Terence Brown (nicknamed Red) who brought him to TRC. Patient was found on Spring Gulch Road near entrance to Amangani. Two birds were found- 1 was dead, and the 2nd was very out of it. Finder scooped up patient, kept in box overnight, and dropped off patient in the AM. 12.4 2:30pm Jason called to check up on bird and ask some questions- SR responded, let him know that patient was in O2, looking good at this stage, but its very much a day-by-day thing. He wanted to know if we were hoping for release- I said yes always of course aiming for that, by we'll have to see how his injuries progress. Not sure about why 2 NSWO were found- maybe roadkill nearby? All speculation.). Fx - Mandible; Fx - Coracoid. Eyes / Ears / Mouth / Nares: Possible broken jaw, no power in bite and it hangs open. Wings / Arms: broken coracoid. BROKEN JAW AND CORACOID.  Possible broken jaw, no power in bite and it hangs open. Eyes, ears, nares, coracoids, wings, spine, feet, legs are all good. Patient is alert, aware, and fighting when trying to catch in enclosure. Patient placed in O2 @ 40% for 24hrs or until acting normal. 0.01cc Metacam diluted to 0.05cc with LRS IM BID for 5 days. Force-fed 20-30g dm until self feeding
--------------------
248 Injury. Fence Stuck - RPL lame, melena, tongue and peripheral limb lacerations, anemia. Eyes / Ears / Mouth / Nares: OU - symmetrical, no fundic exam performed, vision and response while in HLE truck appropriate; tongue has several lacerations, primary wound is L side mid-body of tongue, no active hemorrhage; teeth NSF Neurologic: mentation quiet to lethargic, responsive when approached in HLE truck Heart / Lungs: during sedated procedure, heart sounds decreased and femoral pulses weak; no abnormal lung sounds GI / Vent: large amount of melena around peri-anal region and on rectal exam; otherwise rectal exam wnl, pelvis palpates appropriately; no fluid wave or mass appreciated Musculoskeletal: RPL lame, non-wt bearing in HLE truck, difficult to determine if paresis vs. paralysis of limb due to limited space to move around; during sedated exam, mild to moderate swelling over R hip and at R hock, no palpable fx/crepitus or active luxation - good ROM all limbs including R hip Feathers / Fur / Skin: R medial hock region has 6-8mm diam full thickness wound ~1cm proximal to tibiotarsal joint, small amount of serosanguinous fluid present - similar wound (~4mm diam) at lateral R MC region; numerous adult fleas present; R hip has 8cm diam area of alopecia with hyperpigmentation and 3cm long healed wound/abrasion centrally; dorsal rump at midline and to L side has 10x2cm area of scabbing with no open wound and slightly foul odor Wings / Arms: see Skin Legs / Feet / Hocks: see Skin/MS
--------------------
210 ORPH. Puncture wounds - head, tail, right radial fracture- closed, mid-diaphyseal, flea infestation, thin BCS, Dental abscess, ocular injury- OD. Eyes / Ears / Mouth / Nares: Eyes: Conjunctiva pale pink corneas clear, elevated nictitating membrane and retrobulbar retraction OD, small amount of clear ocular discharge OD, decreased menace response OD, no obvious areas of fluorescein stain uptake, no significant findings on fundic exam, OS -NSF Nares: Bilateral airflow no nasal discharge no stridor/stertor  Mouth: No oral lesions, adult incisors 1/2 present upper arcade, absent incisors 1 and 3 lower, right upper PM 4 has abnormal eruption with gingivitis and active discharge, mucous membranes pale pink moist Ears: Discharge and mild inflammation in external ear canal AU Neurologic: QAR, easily handled with light restraint - r/o age, habituation, weakness secondary to anemia etc Musculoskeletal: Slight crepitus and moderate soft tissue swelling right antebrachium, soft tissue swelling over left -mid forehead Feathers / Fur / Skin: Thin, unkempt haircoat with ventral alopecia, fleas and flea dirt present on dorsum, dermatitis on ventrum, crusting, lichenification, patchy alopecia, scales and discharge mid-tail, puncture wounds left-mid forehead with small amount of purulent discharge Body: Heavy odor of pet shampoo? Wings / Arms: Right antebrachium soft tissue swelling, some crepitus, mid-radius fracture with callus palpable
--------------------
294 Chick/Fledgling - Orphaned (Got a call from Dan with IDFG in the morning that he'd ended up with a young "turkey vulture" (took us all afternoon to realize it was a barn owl!).  Found on the ground near a warehouse - he looked and looked for a nest to no avail.  Transferred via Bev in Swan Valley. Dan noted that he had fed the bird some deer meat last night). Trauma - Head; Fx - Mandible; Chick/Fledgling - Orphaned. Eyes / Ears / Mouth / Nares: Initial exam revealed a swollen are in the upper right area of the mouth, deep bruising on the tip of the beak, and dried blood around both nares.  Eyes swollen shut / don't open well, but bird is still young. BROKEN MANDIBLE. Neurologic: Trauma - Head. Initial exam revealed a swollen are in the upper right area of the mouth, deep bruising on the tip of the beak, and dried blood around both nares.  Eyes swollen shut / don't open well, but bird is still young.  Bird is dirty and has an odor, but is going to the bathroom. Estimate 18-20 days old.
Very unsteady on its feet, cannot stand, but is able to balance on it hocks.
BROKEN MANDIBLE. Bird was willing to take 3 small bites of mouse in the afternoon and about 1/2 mouse during the 6:45p feeding/meds.
Many body feathers starting to come in, but the bird is still 100% covered in down at this point.
Started the bird on fluids (5cc 3-4 times per day), 0.03cc Metacam diluted to 0.1cc with LRS, 0.13cc Baytril and 0.33cc Ampicillin. TRC received transfer approval from USFWS on 4.1.16 to transfer to TRC education program. We put gear on him and moved him to the ed barn
--------------------
227 Appeared injured and not able to fly. B1 - Systemic Disease vs B2 - Toxicosis. Neurologic: Standing but tires easily, full palpebral reflex present OU, mild ataxia when walking and unsteady when standing Musculoskeletal: Slight left wing droop, generalized weakness. A: Adult SATE 4353 presented this afternoon for not being able to fly away when approached. Finder thought patient was injured. On presentation, patient was quiet, severely dehydrated, and emaciated. Patient could walk but easily tired and had generalized weakness with an unsteady stance. Suspect systemic disease vs toxicosis. Patient also had a mild left wing droop - r/o injury vs generalized weakness vs systemic disease. Guarded prognosis assigned to patient at this time - will depend on patient's response to supportive care.
P: Plan to continue IVF (Norm-R or LRS) at 120 ml/kg/d and auscultate patient BID while on IVF. Will plan to administer IVLE 15 ml/kg again tomorrow if indicated. Plan to clean/express cloaca PRN for the first few days then consider d/c. Plan to watch for melena TID and check feet/carpi/keel daily. Will start re-feeding plan at 2-5% P-Care and then switch to WF with 1/8 a Seatab. Plan to administer artificial tears PRN and add in an antibiotic depending on blood work results. If wing droop persists, plan to anesthetize patient for radiographs when stable. Plan to pull IVC in 3-5 days. MMC
--------------------
224 Leg injury. GI / Vent: Dark diarrhea Body: Hypothermic, anemic, generally weak Legs / Feet / Hocks: Dangling L leg, muscle atrophy in area. Large, adhered, crusted wound extending back from knee over thigh ~5cm. When cleaned, excessive bleeding and slow clotting. Dragging or pressure lesions at dorsal surface of foot along joints, worst at D3. PCV 14%, TP 1.2, BC 1. Consulted on case w/DVM. Extent of wound and lack of use of leg indicate poor prognosis, but electing to pursue a night’s stabilization and hydration of wound. During wound care, a single point within wound began to bleed excessively and was only stopped with extended treatment (~10min) with a pressure bandage followed by extremely cautious dressing. Be aware during wound care that disturbance of the clotting over this blood vessel if P is still anemic may result in similar bleeding. Per DVM instruction, dressed with AH, telfa, vetwrap pressure bandage. At end of night, no new bleeding noted within AH, seal on edges of AH appears strong, removed vetwrap/telfa to prevent excessive pressure overnight without monitoring.

Due to potential power outage and hypothermic patient, unable to move P to quarantine space. Provided 2 snuggle safe discs and kept in ICU in wall cage. STRICT quarantine and PPE required in this space. Move to Tuffshed ASAP when threat of power outage not looming
--------------------
219 injured: shot & attacked. NECROPSY RESULTS: Interstitial nephritis (kidney disorder); High velocity projectile trauma T7-8; enlargement of vertebral bodies 7 and 8, and interstitial nephritis. The condition of the spinal cord prevented histologic examination and the exact damage to the spinal cord was unable to be determined. The gross necropsy findings included a thin body condition; alopecia of the head; worn and fractured teeth; absence of three digits; and enlarged vertebral bodies T7-8. The histopathology identified interstitial nephritis with extensive distortion of the renal tubular architecture and suppurative inflammation. The nephritis is likely due to nerve injury allowing an ascending infection/inflammation. The brain, heart, liver, lungs, spleen, and pancreas did not have pathologic lesions present; tested negative for rabies. Eyes / Ears / Mouth / Nares: missing right ear pinna, infected teeth/gums; missing/broken canine/incisors; nasal congestion from infection; scar on forehead; shot in the head; 2 pellets on RADS Neurologic: dragging back legs; shot in back; tail broken and bone exposed Heart / Lungs: pneumonia; GI / Vent: flaccid rectum; prolapsed penis Musculoskeletal: osteomyelitis throughout body at joint; multiple bone Fxs Feathers / Fur / Skin: unkept Body: pellet in liver on RADS Wings / Arms: broken wrist and hand bones; bone infection; pellet in left arm Legs / Feet / Hocks: broken ankles and feet bones; bone infection
--------------------
219 Suspect predator attack, wet?. B1, C - systemic/infectious disease, unknown trauma. Neurologic: depressed mentation Heart / Lungs: harsh bronchovesicular sounds bilateral with increased respiratory effort GI / Vent: asymmetrical testicles- R testicle hypoplastic Musculoskeletal: holding RH limb out at rest- uses all 4 limbs normally when ambulating Feathers / Fur / Skin: fur covered in oil + feces, multifocal strips of alopecia over flanks + dorsum with marked erythema of the skin. A: Adult male cottontail rabbit presents for injuries to the leg and back and concern for wet fur. On physical examination patient is coated in oil and feces with strips of alopecia along the fur coat, depressed mentation, and has evidence of difficulty breathing. The skin is diffusely erythematous concerning for irritation secondary to the oil. Placed under GA for radiographs which reveal diffuse interstitial pattern-concerning for pulmonary edema or diffuse pneumonitis/pneumonia (bacterial, viral). Radiographs demonstrate full GI tract. Concern that patient may have groomed/inhaled oiled substance leading to caustic pneumonitis and potential for secondary bacterial pneumonia. Prognosis guarded to grave given species.
P: 10% BW SQF, TMS 30mg/kg PO BID, Meloxicam 1mg/kg PO SID, wean O2 in 2-3 days, vet check neuro + ausuclt tomorrow, D/c meloxicam in 3 days, d/c TMS in 5 days. FF 10% BW critical care if DNE. Continue baths for oil
--------------------
207 limping, noy flying, lethargic, did not move when approached. B1, B2 - systemic disease vs. red tide/toxicity. Eyes / Ears / Mouth / Nares: White plaques/pustules on dorsal surface of oropharynx. Pouch sticking together. Neurologic: Severely weak, keel-resting and spreading wings when walking. Suspect ataxic rather than lame. Legs / Feet / Hocks: ~0.8 cm old laceration plantar aspect of distal LEFT 3rd digit. A: Adult BRPE presented for limping, not flying, and lethargy. PE showed emaciation, severe dehydration, and weakness. Suspect apparent lameness is severe weakness and ataxia rather than injury. r/o brevetoxicosis vs. renal disease vs. aspergillosis vs. viral infection vs. bacterial infection vs. other toxin vs. other systemic disease. Swab of oral plaques negative for trichomonas - r/o bacterial vs. yeast vs. parasitic.
P: NormR IV @ 50 ml/kg/d. Start metronidazole 25 mg/kg PO BID per RT protocol, gabapentin 15 mg/kg PO BID in case of pain, refeeding plan 3-5% P-care to WF + 1 SeaTab, monitor for melena, cloacoliths, and pododermatitis. Recheck neurologic status and gait daily for next 3 days, obtain PLOP rad 12/29, recheck auscultation and adjust fluid rate as needed 12/29, consider checking chemistry 12/29 or 12/30. Pending stability and clinical progress, HOLD for full rads +/- pull IVC 1/1
--------------------
221 Couldn't fly or stay in water. He was staggering, extending his neck like he was choking. His crop looks enlarged. B1 - Systemic Disease vs B2 - Toxicosis (red tide). Eyes / Ears / Mouth / Nares: Pale pink MM Neurologic: Standing, mild ataxia, mild/moderate head tremors, inconsistent palpebral reflex OU Body: Emaciated. A: Juvenile DCCO 4340 presented for not being able to fly, staggering, and with a enlarged looking "crop" +/- choking. On presentation, patient had mild ataxia and mild/moderate head tremors. Inconsistent palpebral reflex OU as well. Patient is emaciated, moderately dehydrated, and has pale pink MM. Suspect red tide vs other. Patient's prognosis for survival is guarded at this time - will depend on patient's response to supportive care.
P: Patient was enrolled in IVLE study and will receive two doses. Continue IVF (LRS or Norm-R) @ 85 ml/kg/day, Repeat IVLE @ 15 ml/kg over one hour tomorrow. Check neurological status over the next three days and auscultate BID while on IVF. Check CBC results tomorrow +/- add in antibiotic tomorrow. Pull IVC in 3-5 days. Melena watch TID, clean and express cloaca PRN, check feet/carpi/keel SID. Apply artificial tears PRN. Re-feeding plan starting at 2-5% BW P-Care to whole fish. Once on WF 1/2 Seatab SID. Fundic exam OU and fluorescein stain OU planned for tomorrow. MMC
--------------------
235 He was found in the median of the road, no trees anywhere near there.  He was brought into the shelter.  Unknown how he ended on the median. Eyes / Ears / Mouth / Nares: L eye hyphema at 5-7 o'clock - blood on the bottom of the eye, slight bruising on the back of the eye visible in the L ear, blood in the choanal slit, anisocoria - L pupil significantly more dilated than the R;  Ophthalmic exam by AD - OS: dilated and no PLRs, intact but slow palpebral response, hyphema along the 5-7 region of the eye, significant aqueous flare present; large visible blood clot filing the vitreous chamber obscuring the view of the retina but was can be seen appears very pale; OD: very mild amount of aqueous flare; retinal fold/chorioretinal scarring around the pectin, does not appear to have active inflammation/bleeding, PLRs brisk and intact, normal palpebral response; no stain uptake OU, but after flushing eyes patient was not seen having a good palpebral response OS Neurologic: QAR, bitey Heart / Lungs: HR = 150, potentially brachycardia per AD, lung sounds WNL Body: bruising on the cranial-most aspect of the keel where the clavicles meet Legs / Feet / Hocks: RD3 R lateral aspect pinpoint laceration and active bleeding - suspect puncture from another talon, patches of bruising on the R lateral femur - more proximal R femur potentially slightly swollen?,
--------------------
217 Bird found in his backyard, bleeding, thinks it was injured by a wire. Eyes / Ears / Mouth / Nares: Eyes, nares, clear. Some food coming up from crop -- foul smell. Neurologic: QAR but no neuro symptoms, no ataxia, cloacal function normal, good withdrawal Heart / Lungs: Clear heart and breath sounds GI / Vent: Potential crop stasis? Crop and entire esophagus was extremely full (could even see the bolus before examining the bird) with smelly old food; the finder only provided water for this bird so unsure how long that food was in the crop for. Musculoskeletal: Loose L shoulder, crepitus Feathers / Fur / Skin: Some new pin feathers coming in around neck and shoulders, tail feathers dirty. See feet re: skin Body: BCS 1/5 Wings / Arms: L wing hangs a little, R wing had open wound actively bleeding over carpals. Carpals felt loose but fx not obvious. Unable to fly. Legs / Feet / Hocks: Potential frostbite on feet -- feet were cold to the touch despite having been indoors, webbing was a darker gray colour. No sloughing, though. Able to stand and walk normally. Weight was 860 g taken with full crop and full esophagus -- unsure of the mass of that substance but I estimate it weighed approx 50 g
--------------------

In [24]:
%%time
def tok_fn(row):
  from transformers import AutoTokenizer
  ckpt = "distilbert-base-uncased"  
  tokenizer = AutoTokenizer.from_pretrained(ckpt)
  return tokenizer(row["text"], 
                  truncation=True, 
                    padding="max_length", 
                    max_length=128)

#def tok_fn(row):
#    return tokenizer(row["text"], 
#                     truncation=True, 
#                     padding="max_length", 
#                     max_length=128)


tok_ds = ds.map(tok_fn, batched=True, num_proc=16, remove_columns=labels + ["text"])

Map (num_proc=16):   0%|          | 0/10632 [00:00<?, ? examples/s]

Map (num_proc=16):   0%|          | 0/2658 [00:00<?, ? examples/s]

Map (num_proc=16):   0%|          | 0/2346 [00:00<?, ? examples/s]

CPU times: total: 3.02 s
Wall time: 2min 11s

In [25]:
tok_ds

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 10632
    })
    val: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 2658
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 2346
    })
})

In [26]:
tok_ds["train"][0]

{'labels': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 'input_ids': [101,
  2053,
  5776,
  18558,
  1012,
  2205,
  2402,
  102,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [27]:
# Save the processed data in a parquet file
for split,split_ds in tok_ds.items():
    split_ds.to_parquet(f"../data/processed/wndp-api-data-{split}.parquet")

Creating parquet from Arrow format:   0%|          | 0/11 [00:00<?, ?ba/s]

Creating parquet from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

Creating parquet from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

In [28]:
!ls ../data/processed/

'ls' is not recognized as an internal or external command,
operable program or batch file.

In [29]:
%%time
data_files = {
    "train": "../data/processed/wndp-api-data-train.parquet",
    "val": "../data/processed/wndp-api-data-val.parquet",
    "test": "../data/processed/wndp-api-data-test.parquet",
}

ds = load_dataset("parquet", data_files=data_files)

Downloading data files:   0%|          | 0/3 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating val split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

CPU times: total: 844 ms
Wall time: 2.61 s